---
name: Terraform Plan

description: Terraform Plan

inputs:
  AWS_ACCOUNT_ID:
    description: AWS アカウント ID
    required: true
  AWS_ENV_NAME:
    description: 環境名
    required: true
  CHECK_DIFF:
    description: 差分チェックを行うかどうか
    required: true
    default: "_false"
  SLACK_WEBHOOK:
    description: Slack の Webhook URL
    required: true
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: ./.github/actions/setup-terraform
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Terraform Validate
      uses: ./.github/actions/terraform-validate
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Terraform Plan
      continue-on-error: true
      id: terraform-plan
      run: terraform plan -detailed-exitcode -no-color > tf_plan.txt
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Set Terraform Plan status
      if: always()
      run: |
        case "$TF_PLAN_EXIT_CODE" in
          0) TF_PLAN_STATUS="no-changes" ;;
          1) TF_PLAN_STATUS="error" ;;
          2) TF_PLAN_STATUS="has-diff" ;;
          *) TF_PLAN_STATUS="unknown-error" ;;
        esac

        echo "TF_PLAN_STATUS=$TF_PLAN_STATUS"
        echo "TF_PLAN_STATUS=$TF_PLAN_STATUS" >> "$GITHUB_ENV"
      env:
        TF_PLAN_EXIT_CODE: ${{ steps.terraform-plan.outputs.exitcode }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Set Slack Message (Terraform Plan failure)
      if: env.TF_PLAN_STATUS == 'has-diff' && inputs.CHECK_DIFF == '_true'
      run: echo "ERROR_MSG=インフラのコードと実態のリソースに差分があります" >> "$GITHUB_ENV"
      shell: bash

    - name: Set Slack Message (another error)
      if: steps.terraform-plan.outputs.exitcode == '1'
      run: echo "ERROR_MSG=difference check CIがエラー終了しました" >> "$GITHUB_ENV"
      shell: bash

    - name: Slack Notification (failure)
      continue-on-error: true
      if: steps.terraform-plan.outputs.exitcode == '1' || (env.TF_PLAN_STATUS == 'has-diff' && inputs.CHECK_DIFF == '_true')
      uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
      env:
        SLACK_CHANNEL: "#ntf_gh_private-lab"
        SLACK_COLOR: danger
        SLACK_TITLE: "${{ inputs.AWS_ENV_NAME }}(${{ inputs.AWS_ACCOUNT_ID }}): ${{ env.ERROR_MSG }}"
        SLACK_MESSAGE: "<!subteam^U0RFFAK9U> 確認してください。\npath: `${{ inputs.working-directory }}`"
        SLACK_LINK_NAMES: "true"
        SLACK_USERNAME: github-bot
        SLACK_ICON_EMOJI: ":x:"
        SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK }}

    - name: Require successful Terraform Plan
      if: always()
      run: test "$TF_PLAN_STATUS" = no-changes || test "$TF_PLAN_STATUS" = has-diff
      shell: bash
