---
name: AWS Credential

description: AWS Credential

inputs:
  oidc-iam-role:
    description: AWS の認証で使用する OIDC 認証用の ID Provider にアクセスするための IAM Role
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ inputs.oidc-iam-role }}

    - name: Get caller identity
      run: aws sts get-caller-identity
      shell: bash
