---
name: Secrets Manager (test)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency: secrets-manager

env:
  AWS_ACCOUNT_ID: 107662415716
  AWS_ENV_NAME: sandbox
  OIDC_IAM_ROLE: sandbox-private-lab-secrets-manager
  TEST_ENV_PARAM: SANDBOX

jobs:
  get-secrets:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: AWS Credential
        uses: ./.github/actions/aws-credential
        with:
          oidc-iam-role: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.OIDC_IAM_ROLE }}

      - name: AWSSecretsManagerから環境変数にシークレットを読み込みます
        uses: abhilash1in/aws-secrets-manager-action@2cc6ddf66834f7c9432cbcf5846f6d98286be155 # v2.1.0
        with:
          secrets: |
            ${{ env.AWS_ENV_NAME }}/test
          parse-json: true

      - name: Check secret availability
        run: test -n "$SANDBOX_TEST_HOGE"
