name: Test Setup Repository Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-setup-repository-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git

      - name: Run setup-repository.sh
        run: |
          chmod +x ./setup-repository.sh
          ./setup-repository.sh

      - name: Verify aws-vault installation
        run: aws-vault --version

  test-setup-repository-macos:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup-repository.sh
        run: |
          chmod +x ./setup-repository.sh
          ./setup-repository.sh

      - name: Verify aws-vault installation
        run: aws-vault --version
