---
name: Terraform Plan - Portfolio (difference check)

on:
  schedule:
    # 毎日 7:00(JST) に実行
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: terraform-aws-portfolio-difference-check
  cancel-in-progress: true

jobs:
  terraform-difference-check:
    permissions:
      contents: read
      id-token: write
      deployments: write
    name: Terraform portfolio
    uses: ./.github/workflows/_terraform-aws-portfolio.yml
    with:
      CHECK_DIFF: "_true"
