---
name: Terraform Validate

description: Terraform Validate

inputs:
  working-directory:
    description: Terraform CLI 実行時のパス
    required: true

runs:
  using: composite
  steps:
    - name: Terraform Validate
      run: terraform validate -no-color
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@6ffdbaa3be476b3431f7275c26966ef32ff60337 # v6.3.2
      with:
        tflint_version: v0.64.0
        checksums: |
          cca9d13e2e1d7a2c627af60ff899a3c9b74212899416aeb96ec764d2ef954537
          560da89aacf59389d4eb029730dd5b109b7288096c32f2726a0d9e783a5ea8eb
          0f3a9fd17526014646a2dfc3f9122f7b4161abe3d6b0f0f03f9014483ddf4d19
          2496e9cb3d24992d553b45e7c87a0fdc9449ca975233876247a9bfeda857e6c0
          fb42fb859d844b156a8ea9d3363078c4d8b85ca78782e60876b08c9b8e59f303

    - name: Show version
      run: tflint --version
      shell: bash

    - name: Init TFLint
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

    - name: Run TFLint
      run: tflint --chdir="$TF_WORKING_DIRECTORY" --call-module-type=all
      env:
        TF_WORKING_DIRECTORY: ${{ inputs.working-directory }}
      shell: bash
